### ISSUE TITLE
Observe Cancellation

### ISSUE THREAD

**Issue by mkovatsc** [OpenMobileAlliance/OMA-LwM2M-Public-Review#11]
CoAP supports two official ways to cancel an observe realtionship:
  - Proactive through a GET request with Observe=1
  - Reactive through empty RSTs in reply to Notifications

GET with Observe=1 should be the preferred way for LWM2M. Reactive cancellation needs to wait for the next incoming Notification and CoAP servers may ignore RSTs for NON Notifications (but MUST mix in a CON Notification once in a while).

These should replace the Write Attribute "cancel" to make use of the available features in CoAP libraries and for conformance with the IETF standard.

**Comment by jpradocueva** [comment]
Added labels to assist with the classification of the issue.

**Comment by ThGarnier** [comment]
This has been fixed in CR04 (2015-01-16) and definitively agreed after plug test. Since then present in TS 1.0
