### ISSUE TITLE
PSK Identity twice in LWM2M Security Object

### ISSUE THREAD

**Issue by mkovatsc** [OpenMobileAlliance/OMA-LwM2M-Public-Review#12]
The LWM2M Security Object defines both Resources 3 and 4 to carry the PSK Identity, but there is only one. Only for public key cryptography the keys differ for Client and Server.

Is this a copy and paste error?

**Comment by jpradocueva** [comment]
Added labels to assist with the classification of the issue.

**Comment by paulszego** [comment]
I don't believe resource 4 is meant for PSK. Section 7.1.1 only mentions resources 3 & 5.

Section2 7.1.2 (raw public key) and 7.1.3 (x509) do use resources 3, 4 & 5.

**Comment by ThGarnier** [comment]
This has been fixed with CR17 R01 (2015-04-21)  and since then TS 1.0 is aligned with that point
