### ISSUE TITLE
Only Write operation in Bootstrap Interface

### ISSUE THREAD

**Issue by mkovatsc** [OpenMobileAlliance/OMA-LwM2M-Public-Review#13]
The Bootstrap Interface does not define the Create operation, although the Bootstrap Server expects the Instance not to exist. The example in Figure 17 shows a Delete, after which no Instances should exist.

The Bootstrap Interface is similar to the Device Management and Service Enablement Interface. Thus, the operations should follow the same logic.

**Comment by jpradocueva** [comment]
Added labels to assist with the classification of the issue.

**Comment by paulszego** [comment]
The last paragraph in section 8.2.2 says:

*"Different from „Write“ operation in Device Management and Service Enablement interface, the LWM2M Client MUST write the value included in the payload regardless of an existence of the targeting Object Instance or Resource."*

If the interface was made consistent then then handling this special case could be removed, further simplifying constrained clients, 

Note however no mention of this is made in section 5, "Interfaces", but only in section 8, "Transport Layer Binding and Encodings". Very convoluted.

**Comment by ThGarnier** [comment]
Yes;  correct alignments between Section 5 and 8 - not only on the point you are mentioning - are addressed in CR046R01 (spec in Sept should reflect these fixes)

**Comment by ThGarnier** [comment]
As said fixed in OMA-TS-LightweightM2M-V1_0-20150910-D
=> Closed
