### ISSUE TITLE
Example shows 2.03 Valid in response to Request Bootstrap

### ISSUE THREAD

**Issue by mkovatsc** [OpenMobileAlliance/OMA-LwM2M-Public-Review#14]
Figure 17 in 8.2.2 Bootstrap Interface shows 2.03 Valid, This should be a 2.04 Changed.

**Comment by jpradocueva** [comment]
Added labels to assist with the classification of the issue.

**Comment by ThGarnier** [comment]
Yes it is noted and should be fixed with the next agreed CR on bootstrap (few have already been refused for other points under discussion e.g.  #39   : so on-going :-)

**Comment by ThGarnier** [comment]
fixed  in CR25R02 (TS-LightweightM2M-V1_0-20150615)
