### ISSUE TITLE
Full usage of the CoAP response codes

### ISSUE THREAD

**Issue by mkovatsc** [OpenMobileAlliance/OMA-LwM2M-Public-Review#16]
Currently, LWM2M picks specific CoAP response codes to inform about certain outcomes of operations. This does not safe complexity or memory on devices. It only complicates debugging: many errors cannot be described properly, although a corresponding code would exist in CoAP.

LWM2M should make use of all the response codes, in particular the error codes and potentially the diagnostic message. If a constrained device needs to safe memory, it could only evaluate the response code class.

**Comment by jpradocueva** [comment]
Added labels to assist with the classification of the issue.
