### ISSUE TITLE
URIs in Test Cases

### ISSUE THREAD

**Issue by mkovatsc** [OpenMobileAlliance/OMA-LwM2M-Public-Review#17]
Each test case should provide the target URI (object/instance/resource).

**Comment by jpradocueva** [comment]
Added labels to assist with the classification of the issue.

**Comment by ThGarnier** [comment]
a new Baseline for ETS has been agreed (July 2015) with a clearer structure in order to easily 
receive new tests cases  (on going that month - August) . Your request regarding a better identification
of the target has been taken into account.

**Comment by ThGarnier** [comment]
Sorry not July but August : OMA-ETS-LightweightM2M-V1_0-20150811-D  :-)
