### ISSUE TITLE
Duplicate int-201 in Test Cases

### ISSUE THREAD

**Issue by mkovatsc** [OpenMobileAlliance/OMA-LwM2M-Public-Review#18]
Test cases 6.2.1 through 6.2.3 use the same label "int-201"

**Comment by jpradocueva** [comment]
Added labels to assist with the classification of the issue.

**Comment by ThGarnier** [comment]
This has been solved in OMA-ETS-LightweightM2M-V1_0-20150811-D (August 2015)
