### ISSUE TITLE
Explicitly Test Operations

### ISSUE THREAD

**Issue by mkovatsc** [OpenMobileAlliance/OMA-LwM2M-Public-Review#19]
The test cases should primarily be about testing all the different operations on different levels (Object/Instance/Resource). The current test spec randomly tests Object functionality and covers different operations rather by chance.

**Comment by jpradocueva** [comment]
Added labels to assist with the classification of the issue.

**Comment by ThGarnier** [comment]
Not perfect but this point is (I hope) better addressed in the new Baseline OMA-ETS-LightweightM2M-V1_0-20150811-D
