### ISSUE TITLE
Wording in Test Cases

### ISSUE THREAD

**Issue by mkovatsc** [OpenMobileAlliance/OMA-LwM2M-Public-Review#20]
6.2.6 uses "terminal," which is not defined in LWM2M.

6.5.1 uses "Line Voltage" -- should be "Power Source Voltage"

**Comment by jpradocueva** [comment]
Added labels to assist with the classification of the issue.

**Comment by ThGarnier** [comment]
Restructuring Test Cases document also for adding new tests, is on going (CR submitted to IOP group); very few modifs for this 1st step except for issue#20 and #18 which have been fixed here.
Hope new ETS including the new test cases will be available for end of August :-)

**Comment by ThGarnier** [comment]
Solved with the availaibility of the new ETS : OMA-ETS-LightweightM2M-V1_0-20150811-D
