### ISSUE TITLE
Additional object resources in OMA-TS-LightweightM2M-V1_0-20141126-C

### ISSUE THREAD

**Issue by vogtdominik** [OpenMobileAlliance/OMA-LwM2M-Public-Review#23]
In OMA-TS-LightweightM2M-V1_0-20141126-C some resources were added:
Device: Resource ID 17 - 21
Firmware Update: Resource ID 6 - 7

Will these additional resources be added to the 'object description files' (TXT files) included in the enabled release?

Btw. the resources in the Device object in chapter E.4 (OMA-TS-LightweightM2M-V1_0-20141126-C) are not sorted by Resource ID.

**Comment by ThGarnier** [comment]
These resources are fully support by TS 1.0 so all documents have to be updated accordingly.
The reason the resources are not sorted by ID, is it seemed better (it's a choice) to group (new and initial) resources which have some relationship, instead to follow the strict numerical order (of course the initial resources must kept their IDs) .
