### ISSUE TITLE
Integer resources with no value

### ISSUE THREAD

**Issue by BillBennett** [OpenMobileAlliance/OMA-LwM2M-Public-Review#25]
I've come across situations where a resource of type integer doesn't currently have a value. Usually this occurs when a device supports a feature but some error condition is currently causing that feature to be unavailable.
How should the client handle reads of the value?

The options I've tried so far:
* Return a zero-length text representation or a TLV representation with no resource. Makes sense to me but some servers I've tried generate an error.
* Return some default value. May be OK for some resources but not good in the general case.
* Return 404 not found. It concerns me that some servers may take that to mean "This resource is not implemented", particularly for optional resources.

**Comment by ThGarnier** [comment]
"Return 404 not found"  is the right answer.  For optional resources, the Server should use the Discover command to be aware whether a  resource is implemented or not.
