### ISSUE TITLE
Notifications (2.04 vs 2.05)

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/OMA-LwM2M-Public-Review#3]
TS LwM2M section 8.2.5.
CoAP recommends to send `2.05 Content` as response code for Notifications but OMA defines `2.04 Changed` instead.

**Comment by jvermillard** [comment]
to be noted 2.04 (changed) is mean to be used when no content is return, like a write message. So 2.04 observe notification won't be cached by CoAP or  HTTP caches

**Comment by ThGarnier** [comment]
OMA LwM2M  1.0  now  (CR07 12/02/2015)  send 2.05 Content as response code for Notifications
