### ISSUE TITLE
Clarify usage of create/update on object instances with R-only resources

### ISSUE THREAD

**Issue by boaks** [OpenMobileAlliance/OMA-LwM2M-Public-Review#30]
When resources are R-only, what must then be obeyed using the operation create or replace on object instances?

Example:
An object (id 50000) defines to have a mandatory R-only resource (ID 1, water level, R, S, M, …).
To create a new instance of 50000, must the resource with ID 1 be provided?
To replace a instance of 50000, must/could the resource with ID 1 be provided?

**Comment by msangoi** [comment]
A typical example is the Software Management object. 
When a new instance is created, how do we provide the mandatory R-only resources 'PkgName' and 'PkgVersion'?

**Comment by boaks** [comment]
"OMA-DM-LightweightM2M-2015-0033R01-CR_R_Only_Resource_Clarification.doc" will clarify it.

But why does it introduce a different processing of mandatory (use new value) and otional (ignore new value)?

    •	For the “Delete”, “Observe”, “Write Attributes”, and “Discover” operations, the LWM2M Client
    MUST perform the operation since those operations have no effect on the Resource.

"Observe" should be moved to the "Read" above, though it includes a initial read.

**Comment by boaks** [comment]
Fixed with OMA-TS-LightweightM2M-V1_0-20150615-D.
