### ISSUE TITLE
Handle multiple write attributes (update/replace)

### ISSUE THREAD

**Issue by boaks** [OpenMobileAlliance/OMA-LwM2M-Public-Review#31]
When attributes are written multiple times, should this be handled as update or  as replace?

Example:
1. write attrib /3/0/9?lt=30
2. write attrib /3/0/9?gt=70

Is the result "gt=70" or "lt=30&gt=70"?

**Comment by ThGarnier** [comment]
Yes the result is  "lt=30&gt=70", since each Write Attributes is targeting 2  different attributes

**Comment by boaks** [comment]
Thanks!
