### ISSUE TITLE
Definition of online/offline 8.3/8.4 related to UDP

### ISSUE THREAD

**Issue by boaks** [OpenMobileAlliance/OMA-LwM2M-Public-Review#32]
Is offline/online only defined by "not sending/receiving a message from the client" for ACK_TIMEOUT?
Must a server stop retransmissions, when not receiving an ACK in time?
Or should the server retry and only stop, when the maxium retries are reached?

**Comment by boaks** [comment]
See https://github.com/OpenMobileAlliance/OMA-LwM2M-Public-Review/issues/35

**Comment by alex-ellwein** [comment]
+1, this is not clear from the spec.

**Comment by ThGarnier** [comment]
Fixed in since OMA-TS-LightweightM2M-V1_0-20150910-D, still improved in   OMA-TS-LightweightM2M-V1_0-20151211-D
=> to be closed

**Comment by boaks** [comment]
OMA-TS-LightweightM2M-V1_0-20151211-D:
"The LWM2M Client MUST wait at least ACK_TIMEOUT [COAP] seconds from the last CoAP message it sent to the LWM2M Server before intentionally going offline."

RFC7252, 4.8, Transmission Parameters, 
ACK_TIMEOUT = 2 seconds
ACK_RANDOM_FACTOR = 1.5

So this defines, that a client must wait at least 2 seconds, right?
Should sending an ACK or RST from the client to the server also trigger this timeout, because these are messages to (in the meaning of RFC7252)?
And it doesn't take in account, when the client receives messages from the server. also right?

**Comment by boaks** [comment]
Uuups sorry, I forgot, that the  later

OMA-TS-LightweightM2M-V1_0-20151211-D:
2.	The LWM2M Client uses the CoAP ACK_TIMEOUT parameter to set a timer for how long it shall stay awake since last sent message to the LWM2M Server. After ACK_TIMEOUT without any messages from the LWM2M Server, the LWM2M Client SHOULD sleep until sending next periodic “Update” operation.

Defines dependencies on receiving messages from the server.

**Comment by ThGarnier** [comment]
:-)  so can be closed ?

**Comment by boaks** [comment]
Hm, yes.

(But, if the addition of receiving a message from the server would be added also above, I would feel better :-)  ).

**Comment by Megan-OMA** [comment]
Issue closed per agreement.

@ThGarnier, please note final comment.
