### ISSUE TITLE
Bootstrap sequence: when should a client try to register after a bootstrap has started?

### ISSUE THREAD

**Issue by boaks** [OpenMobileAlliance/OMA-LwM2M-Public-Review#35]
“5.1.3 Bootstrap Sequence” doesn’t contain information on what should be done, after the bootstrap started. Especially, it doesn’t contain information, when the client should try to register at a LWM2M server after the bootstrap has started. There is no specification, when the client should assume, that the bootstrap is finished.

Should therefore the "lifetime" be used as timeout for the bootstrap? e..g whon no write nor delete is received for longer then lifetime, the the bootstrap is assumed to be finished and the client shoul try to register ar a LWM2M server.

**Comment by jvermillard** [comment]
:+1:  this is not clear
My interpretation is we should wait the max coap transmit time like for queue mode..
anyway the server sending a end of bootstrap would simplify this code, like an EXEC on / or whatever

**Comment by boaks** [comment]
"My interpretation is we should wait the max coap transmit time like for queue mode."

Hm, LWM2M TS, page 63, mention the ACK_TIMEOUT for queue mode, which significantly smaller then MAX_TRANSMIT_WAIT (e.g. 2s instead of 93s).
So I guess, the time for the queue mode should be checked.

See https://github.com/OpenMobileAlliance/OMA-LwM2M-Public-Review/issues/32

**Comment by boaks** [comment]
"OMA-DM-LightweightM2M-2015-0025R01-CR_Bootstrap_Finish.docx" will fix it.

**Comment by boaks** [comment]
Fixed with "OMA-TS-LightweightM2M-V1_0-20150615-D".

May be section 5.2. should also mention the "Bootstrap Finish" of 8.2.2.
