### ISSUE TITLE
add an Internal Server Error 500

### ISSUE THREAD

**Issue by sbernard31** [OpenMobileAlliance/OMA-LwM2M-Public-Review#36]
The LwM2m Spec define possible response codes  for each request (§8.5).
I think this response code [Internal Server Error 500](http://tools.ietf.org/html/rfc7252#section-5.9.3) is really needed, for unexpected situation ! 

(Currently, when an error occured in leshan we return a bad request but an exception raised at server/client side is not a bad request ...)

**Comment by boaks** [comment]
There is currently already a proposal for the extensions of the error code.

See https://github.com/OpenMobileAlliance/OMA-LwM2M-Public-Review/issues/16

**Comment by ThGarnier** [comment]
fixed  in CR26R01 (TS-LightweightM2M-V1_0-20150615)
