### ISSUE TITLE
Firmware update: missing result value when the update is failed

### ISSUE THREAD

**Issue by msangoi** [OpenMobileAlliance/OMA-LwM2M-Public-Review#38]
With the current values available for the update result resource (/5/0/5), there is no way to indicate that the firmware installation has failed.

This is not consistent with the update results defined for the SW update, where the value 10 (Software installation failure) can be used.
Note that value 9 (Device defined update error) is also defined for vendor specific errors. But this is not clear to me how to use and if it is restricted to a single error code.

**Comment by ThGarnier** [comment]
The CR043 is on-going (August) to address these issues

**Comment by ThGarnier** [comment]
However, value 9 you are mentioning is not a valid value as long as Firmware Object is concerned (topic of your issue#38) . Are you referring to SW Object ? is it something you think needed for Firmware Object (with clarified usage) ?   please explain

**Comment by fdur** [comment]
Hi, what Manuel explained is that supporting a specific error value fo FW update failure linked to the update mechnaism itself could be useful. This error code was defined for object 9 but not fot object 5

**Comment by msangoi** [comment]
A new value was defined for the Update Result resource (of FW object):
```8: Firmware update failed```

Can be closed.

**Comment by ThGarnier** [comment]
Closed related to TS 1.0 2015-09-10
