### ISSUE TITLE
Pre-Shared Key (PSK) length 

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/OMA-LwM2M-Public-Review#4]
TS, section E.1.1.1
`Clients and Servers MUST support a PSK Identify of *at least 128 bytes* in length as required by [RFC4279].`

*But in RFC4279:*
5.3 Requirements for TLS Implementations
TLS implementations supporting these ciphersuites MUST support arbitrary PSK identities *up to 128 octets in length*, and arbitrary PSKs up to 64 octets in length.

This discrepancy should be resolved.

**Comment by BillBennett** [comment]
From the same TS section:
>The default PSK Cipher Suites defined in this specification use a 128-bit AES key. Thus this key would be represented in 16 bytes in the Secret Key Resource.

This also conflicts with the RFC4279 quote - PSK length is not (directly) related to cipher key size.

**Comment by BillBennett** [comment]
Just realised this is fixed in later documents. Should the issues be closed as they're fixed, or at the next Candidate?

**Comment by ThGarnier** [comment]
Yes this has been fixed by CR17R01 (2015-04-21) : and TS has been updated
