### ISSUE TITLE
Empty data type for execute-only resources

### ISSUE THREAD

**Issue by kralikba** [OpenMobileAlliance/OMA-LwM2M-Public-Review#40]
In OMA-TS-LightweightM2M-V1_0-20141111-D, Appendix D., section D.1, the _Type_ field is specified  as "Data Type indicates the type of Resource value. Data Types used in this enabler are described in Appendix C Data Types.".
I interpret this so that the _Type_ field may never be empty. However, resources only having an "Execute" operation typically have this field blank and the LWM2M.xsd also accepts the blank value as a type.
I would suggest codifying this rule in the Technical specification.

**Comment by ThGarnier** [comment]
Yes this is addressed (among other points) in the submitted CR044 (August)

**Comment by ThGarnier** [comment]
OMA-TS-LightweightM2M-V1_0-20150910-D fixed that issue 
=> to ber closed
