### ISSUE TITLE
Object 7 ( Connectivity Statistics  ) collection duration

### ISSUE THREAD

**Issue by fdur** [OpenMobileAlliance/OMA-LwM2M-Public-Review#41]
In TS, for object 7 (in appendix E):
This LWM2M Objects enables client to collect statistical information and enables the LWM2M Server to retrieve these information, set the collection duration and reset the statistical parameters.

But the collection duration is not really set.
Collection is launched when an EXEC command is sent on /7/0/6 (StartOrReset), so there are no duration concept.
Moreover, it may be not possible to stop a collection "duration", when the collection is launched, it's only possible to reset all counters but not to stop collecting data.
Or do any device reset could be considered as a duration stop ? (meaning that an EXEC command shall be sent on /7/0/6 to launch again the collection ?)

**Comment by Megan-OMA** [comment]
@ThGarnier will you please provide a final comment on why this issue is to be closed before we close it

**Comment by ThGarnier** [comment]
In TS 1.0 20260202 ; this point has been revisited and 2 Exec Resources (Start and Stop) have replaced  the StartOrReset single resource

**Comment by Megan-OMA** [comment]
Thank you very much, @ThGarnier ! Issue now closed. (March 17, 2016)
