### ISSUE TITLE
Object 9 (Software Management) Update State range

### ISSUE THREAD

**Issue by mkovatsc** [OpenMobileAlliance/OMA-LwM2M-Public-Review#45]
The OMA-TS-LWM2M_SwMgmt document defines a range of 1-4, while the description lists states 1-5.

Usually state enumerations start with 0 in LWM2M. Thus, fix to range 0-4 in both columns.

**Comment by ThGarnier** [comment]
Yes :  fixed   in CR24R04 (TS-LWM2M_SwMgmt-V1_0-20150610). Same issue for Firmware Mgmt which will be solved (on going work) in relation to issue#38 (with few other features)
