### ISSUE TITLE
What Value Type must be used for the Attributes which are described in Chapter 5.1

### ISSUE THREAD

**Issue by ingoschaal** [OpenMobileAlliance/OMA-LwM2M-Public-Review#47]
In Chapter 5.1.2 "Attributes Classification" for the following Attributes the Value Type Integer is specified.
Minimum Period
Max imum Period
Greater Than
Less Than
Step

In Chapter 5.4.2 "Discover" some examples are listed in which a floating-point value is used and not the integer value which is specified in Chapter 5.1.2 Attributes Classification.
e.g:
</3/0/7>;ep=1;dim=8;gt=50;lt=42.2,
</3/0/7>;ep=2;dim=8;pmax=300;gt=80;lt=75.5

What Value Type must be used Integer or floating-point?

**Comment by softgearko** [comment]
pmax, pmin are related to the Lifetime, which mentioned at Resource ID 1 in LWM2M Server Object. (Appendix E.2). Lifetime type is integer and unit is seconds in Resource definitions. Therefore, pmax, pmin types should be 'integer' type.
gt, lt, st are related to real values. I think it should be float types.

**Comment by mjkoster** [comment]
Pmin and Pmax are in units of seconds. In order to represent fractional seconds, I have found it useful to use float type for pmin and pmax.

**Comment by ThGarnier** [comment]
Yes this has been fixed by CR35R02 (2015-06-09) : and TS has been updated (gt, lt, st are  real values, pmin & pmax still are integer values)
