### ISSUE TITLE
8.2.2 Bootstrap Interface / DELETE Resource? 

### ISSUE THREAD

**Issue by boaks** [OpenMobileAlliance/OMA-LwM2M-Public-Review#51]
8.2.2 Bootstrap Interface says:

    "The Write or Delete operation targets to an Object Instance or a Resource."

So, should this introduce a "DELETE" for Resources?

**Comment by HAli786** [comment]
Object instance delete will delete all resources associated for that instance.
There is a wild card delete for all objects except LWM2M server account.

Are you looking for multiple resources delete from one object in one operation?

**Comment by joakimeriksson** [comment]
Where is this wild card delete described? Is it DELETE / or DELETE /1 (e.g. all objects and their instances or all instances of a specific object).

**Comment by HAli786** [comment]
Not 100% sure but In my view, the following text in 8.2.2 talks about optional delete of all object instances....

Delete operation MAY target to “/” URI to delete all the existing Object Instances except LWM2M Bootstrap Server Account in the LWM2M Client for initializing before LWM2M Bootstrap Server sends Write operation(s) to the LWM2M Client.

And the example in table 18 appears to indicate that method is delete all resources associated with {Object Instance}

Delete
DELETE
/{Object ID}/{Object Instance ID}
2.02 Deleted
4.05 Method Not Allowed

**Comment by joakimeriksson** [comment]
I do think a DELETE / is a bit "brutal" and there is a factory-default in the device instance that probably would be the better way to truly get the device back to factory default configuration. I would very much prefer the deleter to know at least which of the object that are supposed to be deleted. And from what I read in the specification I had it was all object instances but not all objects and their instances.

BTW: which OMA LWM2M technical specification are we reviewing here? The one that is available as a PDF on the OMA site from (november 2014)?

**Comment by HAli786** [comment]
Yes November 2014 is the spec that I referred to.

**Comment by boaks** [comment]
"Are you looking for multiple resources delete from one object in one operation?"

No, I was just wondering, why the wording is symetric (write and delete targets the same). If a "delete" should not target a resource, may be the TS can clarify this by more proper wording.

**Comment by ThGarnier** [comment]
Yes you are right Achim,thanks ,the sentence in the TS will be changed soon in "The Delete operation targets an Object Instance while the Write operation targets an Object Instance or a Resource"

**Comment by ThGarnier** [comment]
This point is addressed in the submitted CR046  (August)

**Comment by ThGarnier** [comment]
addressed and fixed in  OMA-TS-LightweightM2M-V1_0-20150910-D
=> to be closed

**Comment by boaks** [comment]
Your right, this is fixed in the TS and could be closed.

**Comment by Spongman** [comment]
so how is one supposed to 'un-set' the value of an optional resource?
