### ISSUE TITLE
Bootstraping from smartcard (Section 5.1.3)

### ISSUE THREAD

**Issue by HAli786** [OpenMobileAlliance/OMA-LwM2M-Public-Review#52]
Hello All,

In section 5.1.3 of OMA-TS-LightweightM2M-V1_0 (Nov 26, 2014), it says:

The LWM2M Client MUST follow the procedure specified as below when attempting to bootstrap a LWM2M Device:
1. If the LWM2M Device has Smartcard, the LWM2M Client tries to obtain Bootstrap Information from the Smartcard using the Bootstrap from Smartcard mode.

Regarding "smartcard" mode, I will like to know what UICC files / storage space are supposed to store the LwM2M server address and security information. In case you have a reference to ETSI/3GPP or any other UICC specification that covers storing of the boostrap info.

Thank you

**Comment by ThGarnier** [comment]
The bootstrap info and files are described in Annex G of the TS 
Not limited to Smartcard mode, the Bootstrap Information will contains the Objects (Server, Security ..) which when  deployed in the LWM2M Client, will allow to connect  the LWM2M Server(s).

**Comment by HAli786** [comment]
Thank you very much for pointing me to the appendix g
