### ISSUE TITLE
Do we have a strategy to support 2 bootstrap servers?

### ISSUE THREAD

**Issue by gdotien** [OpenMobileAlliance/OMA-LwM2M-Public-Review#54]
Hi all,

Based on the LWM2M spec, it seems that we only assume that we have 1 bootstrap server that can provision one or multiple DM server. In the future, do we forsee that the device side has to support another bootstrap server, in which case DELETE /  or PUT /1/x and PUT /2/x should be closely controled to avoid accidental clash with the DM information provisionned by the other bootstrap server. What is our plan there?

Thanks a lot

Giang

**Comment by jvermillard** [comment]
The spec state you can have at most one bootstrap server, so no

**Comment by ThGarnier** [comment]
right !
=> to be closed

**Comment by gdotien** [comment]
So to support att lwm2m dm server and avms dm server, should sierra or att bootstrap server be used to provision the other dm server?

Thanks a lot

Giang

Sent from my iPhone

On Dec 17, 2015, at 5:42 AM, Julien Vermillard <notifications@github.com<mailto:notifications@github.com>> wrote:


The spec state you can have at most one bootstrap server, so no

**Comment by Megan-OMA** [comment]
@ThGarnier Will you address this final question before the issue is closed

**Comment by gdotien** [comment]
I am OK with the fact that the carrier and the provider should have a talk to figure this out to make there is only one bootstrap server at any time. 

So we can close this issue.

Thanks a lot

Giang

**Comment by ThGarnier** [comment]
Megan, please the msg is clear

**Comment by Megan-OMA** [comment]
Thank you, everyone.
