### ISSUE TITLE
Strange negative integer representation

### ISSUE THREAD

**Issue by jvermillard** [OpenMobileAlliance/OMA-LwM2M-Public-Review#55]
Extract of the spec:
> Represented as a binary signed integer in network byte order, where the first (most significant) bit is 0 for a positive integer and 1 for a negative integer. The value may be 1 (8-bit), 2 (16-bit), 4 (32-bit) or 8 (64-bit) bytes long as indicated by the Length field. 

Does that mean we need to use a "signed magnitude representation" when every processor in the world now use natively two's complement?

IMO using signed magnitude representation as the spec weakly imply is a mistake and have no real rationales.

And an example with a negative value should be added for disambiguation.

**Comment by BillBennett** [comment]
For storage/use on the device I don't think it matters how you do it. It's mostly a problem when encoding TLV as far as I can see.
I agree it's ambiguous - it seems that two's compliment satisfies the definition too.

Semi related: when sending some values (e.g. resource 0//10 Short Server ID) you may need to use the next integer size if the top bit happens to be set. I think that TLV could support other integer sizes (e.g. 3-byte) for this purpose.

**Comment by ThGarnier** [comment]
Addressed in the submitted CR50 (August)

**Comment by ThGarnier** [comment]
fixed in OMA-TS-LightweightM2M-V1_0-20150910-D
=> to be closed
