### ISSUE TITLE
Creation of  "Access Control" (OID 2) instances

### ISSUE THREAD

**Issue by boaks** [OpenMobileAlliance/OMA-LwM2M-Public-Review#57]
The new OMA-TS-LightweightM2M-V1_0-20150615-D says in 7.3.2.3, "create", last sentence:

    The values of the Read-only Resources MUST be setup by the LWM2M Client only. When a value is
    present in the “New Value” parameter, this value is simply ignored.

Was it intended that “Access Control” (OID 2) instances could then not be created using the device management interface, though the “Object ID” (RID 0) and “Object instance ID” (RID 1) are read only? If so, does it imply, that Access Control” (OID 2) instances  are only created via the bootstrap interface?

**Comment by ThGarnier** [comment]
It should work :) Even if Server provides info on Object Instance ID  to the Client, the Client - in that device management case -  is fully aware  of what it has to do with this value. The best illustration is when the Object Instance ID (OID2)  is not provided, the Client has even to determin which value is pertinent to it (before to write it). So in this case, this OID2 is really "managed" by the Client. It is different for a more Application oriented resource (or Object), for which the Client has no idea  about such a resource; so Client will not take initiative to do anything on it; if this resource is R-only, only a bootstrap message will be able to set it.

**Comment by boaks** [comment]
Thanks! Your right, "It should work :)".
I (re-)read  LWM2M TS 7.3.1.2.1, which defines, that Access Control Objects are either created direct via Bootstrap or indirect via creating "other object instances".

But I could find information related to this two cases:
- What should happen on the "Access Control Objects", if the Bootstrap Server creates a instance of an other object (e.g. a "Server Instance OID 1)")?
- What should happen on the "Access Control Objects", if the LWM2M client creates a instance (default?) of such an other object?

**Comment by ThGarnier** [comment]
In fact these 2 bullets are addressing different purposes : 
. during bootstrap : the instantiation of one Access Control Object (e.g /2/0) per Object (e.g. OID 5000) is triggered by the Client. This creates a placeholder, in which an ACL  will be setup later (Bootstrap Write) for Server which will have the rights to create Instance(s) of that Object (OID 5000).   
. In usual life, a Server "A" could use the "Create" command for instantiating an Object (OID :5000) It will have the right to do that, if that Object has an associated  Access Control Object (created according to the 1st bullet: e.g. /2/0) for which an ACL instance is referring that Server "A". When the Object Instance is created, a new Instance of Access Control Object will be created as well (e.g. /2/1, allowing this Server to setup access rights (R,W,E,D) to other Servers B, C, D  for that Object Instance.
Hope it clarifies a bit 
Th

**Comment by surendravl** [comment]
I am a fresh buddy on leshan. Wanted to know the below:

Does leshan bootstrapping support ACL?

We have implemented the bsstore and wrote our own implementation for ACL objects. but some how our client is not getting the write request for ACL.

Below is the log:
[servers={0=ServerConfig [shortId=1, lifetime=120, defaultMinPeriod=1, defaultMaxPeriod=null, disableTimeout=null, notifIfDisabled=true, binding=U]}, security={0=ServerSecurity [uri=coap://omadmnew.movimentogroup.com:5683, bootstrapServer=true, securityMode=NO_SEC, publicKeyOrId=[], serverPublicKey=[], smsSecurityMode=NO_SEC, smsBindingKeySecret=[], serverSmsNumber=, serverId=111, clientOldOffTime=1, bootstrapServerAccountTimeout=0], 1=ServerSecurity [uri=coap://omadmnew.movimentogroup.com:5683, bootstrapServer=false, securityMode=NO_SEC, publicKeyOrId=[], serverPublicKey=[], smsSecurityMode=NO_SEC, smsBindingKeySecret=[], serverSmsNumber=, serverId=1, clientOldOffTime=1, bootstrapServerAccountTimeout=0]}, accessControl={0=AccessControl [objectId=5, objectInstanceId=65533, acl=0b0000000000011101, aclOwner=1], 1=AccessControl [objectId=5, objectInstanceId=65533, acl=0b0000000000011101, aclOwner=1], 2=AccessControl [objectId=5, objectInstanceId=65533, acl=0b0000000000011101, aclOwner=1], 3=AccessControl [objectId=5, objectInstanceId=65533, acl=0b0000000000011101, aclOwner=1]}]

But server could not get the write request for ACL.

Appreciate your help.

**Comment by boaks** [comment]
Please place your leshan question at

https://github.com/eclipse/leshan/issues
