### ISSUE TITLE
Client and Server implementations

### ISSUE THREAD

**Issue by HAli786** [OpenMobileAlliance/OMA-LwM2M-Public-Review#64]
Hello

Are the names of client and server implementations available in public domain who participated in Test Fest Jan 2015?

Thank you

**Comment by github-oma** [comment]
Unfortunately, the default approach at this test events is not to disclose the name of companies that have participated. 
The report provided to the Working Group IOP can be found in the following link:

http://member.openmobilealliance.org/ftp/Public_documents/IOP/2015/OMA-IOP-2015-0033R01-INP_OMA_LwM2M_TestFest_and_Workshop_Dusseldorf_Jan15.zip
