### ISSUE TITLE
Define network serialization format for the Float type

### ISSUE THREAD

**Issue by cdealti** [OpenMobileAlliance/OMA-LwM2M-Public-Review#65]
There is no general consensus on how an IEEE 754 floating point number should be sent over the network.

**Comment by jvermillard** [comment]
For me it's clear it should sent as big endian

**Comment by ThGarnier** [comment]
Yes, big endian, the spec (January 2016) will clarify it

**Comment by ThGarnier** [comment]
solved with TS 20160202
