### ISSUE TITLE
Errata: 6.3.3.1 Single Object Instance Request Example

### ISSUE THREAD

**Issue by cdealti** [OpenMobileAlliance/OMA-LwM2M-Public-Review#66]
6.3.3.1 Single Object Instance Request Example
Errata: Since the Device Object has no Instances...
Corrige: Since the Device Object has exactly one Instance...

More in general the spec should clearly state that the Object Instance TLV
is not needed if the Object has only one instance.
Similarly a Multiple Resource TLV is not needed if the Resource has only one value.

**Comment by ThGarnier** [comment]
Certainly you're refering an old specification : sorry 
 in general : I expect TS 1.0  2015120811 fixed all your points 
=> To be closed

**Comment by Megan-OMA** [comment]
Closed per ThGarnier comment this issue will be addressed in TS 1.0 2015120811
