### ISSUE TITLE
Addressability of resource instances

### ISSUE THREAD

**Issue by mjkoster** [OpenMobileAlliance/OMA-LwM2M-Public-Review#68]
Resource instances should be individually addressable, for example {"n":"A/0/0/1","ov":"B:1"} in Sec. 6.3.4 of the TS shows a path to a resource at A/0/0/1.

For compatibility with REST and hypermedia systems, the Resource Instance A/0/0/1 in this example should be addressable and reachable as a CoAP resource, and support GET, PUT, POST and DELETE operations.

**Comment by Megan-OMA** [comment]
@ThGarnier Will you please provide a final comment on why this issue should be closed before we do so

**Comment by ThGarnier** [comment]
In TS 1.0, it's to late to  address such deep features (and the side effects); should be considered in TS 1.1 Time frame

**Comment by mjkoster** [comment]
That's reasonable, thanks

**Comment by Megan-OMA** [comment]
Issue closed March 17, 2016 per above comments
