### ISSUE TITLE
Errata B.1.4 SCR for LWM2M Client - Information Reporting

### ISSUE THREAD

**Issue by softgearko** [OpenMobileAlliance/OMA-LwM2M-Public-Review#73]
In section B.1.4 in OMA-TS-LightweightM2M-V1_0-20141116-D, it should be:
LWM2M-IR-001-C-M	Support of “Observe" operation	Section 5.3.1
LWM2M-IR-002-C-M	Support of “Notify” operation	Section 5.3.2
LWM2M-IR-003-C-M	Support of “Cancel Observation” operation	Section 5.3.3

**Comment by ThGarnier** [comment]
Obsolete reference B1.4 OMA-TS-LightweightM2M-V1_0-20141116-D
Seems ok in : OMA-TS-LightweightM2M-V1_0-20151208
=> Closed
