### ISSUE TITLE
Unit for the Bootstrap Server Account Timeout

### ISSUE THREAD

**Issue by jvermillard** [OpenMobileAlliance/OMA-LwM2M-Public-Review#74]
According to the object 0 description (Appendix DD.)

```
The LWM2M Server SHOULD purge the
LWM2M Bootstrap Server Account after
successful bootstrapping. If it has not
already been purged, the LWM2M Client
MUST purge the LWM2M Bootstrap
Server Account after the timeout value
given by this resource. The lowest timeout
value is 1.
If the value is set to 0 the Bootstrap Server
Account lifetime is infinite.
```

What is the timeout unit? seconds?

**Comment by jpradocueva** [comment]
@jvermillard That's correct the timeout unit is expressed in seconds.

**Comment by jvermillard** [comment]
I trust your answer joaquin but I think the best way to fix that is to specify it in the spec :)

**Comment by ThGarnier** [comment]
The TS 1.0 has been fixed regarding that point (maybe in June) .Anyway the last TS 20151211 includes this fix 
=> Closed
