### ISSUE TITLE
MSISDN as an Integer?

### ISSUE THREAD

**Issue by jvermillard** [OpenMobileAlliance/OMA-LwM2M-Public-Review#75]
In the object 0, resource 9 is the Server MSISDN (phone number)
the type is Integer.

That doesn't work a phone number is larger than a 32bit integer:
https://en.wikipedia.org/wiki/MSISDN
Example: 46734962806 is 46 billions
Solution: use String

**Comment by fdur** [comment]
For international number, the prefix may be +
To call franch number: +33<number>
So may be better to use a string
+ = 00 in France
+ = 011 in the US 
So the "+" char needs to be included in this number

**Comment by ThGarnier** [comment]
Yes you are right,take the point,  should  be modified in the first release of 2016 (String)

**Comment by Megan-OMA** [comment]
Closed per ThGarnier comment the issue will be addressed in 2016 first release.
