### ISSUE TITLE
OMA-DM-LightweightM2M-2015-0063-CR_Conn_stats_coll_duration

### ISSUE THREAD

**Issue by boaks** [OpenMobileAlliance/OMA-LwM2M-Public-Review#78]
The definition of resource 6 "StartOrStop" may be difficult to be implemented.
It relies on the effecitve filtering of retransmission. When a request is received twice (in case of a lost acknowledge), the effective behaviour would not be the intended one.

Therefore I would recommend to use an other execute resource for "stop".
(And a read resource for the "state: started/stopped" may also be useful.)

**Comment by jvermillard** [comment]
This is definitively not restful, I agree two resources are better like in object 9 (actived and desactived)

**Comment by boaks** [comment]
Fixed with OMA-TS-LightweightM2M-V1_0-20160125-D.
