### ISSUE TITLE
Resetting Attributes

### ISSUE THREAD

**Issue by kFYatek** [OpenMobileAlliance/OMA-LwM2M-Public-Review#79]
Is there any way to reset the value of the [NOTIFICATION] class attributes? E.g. after following calls:

- Write Attributes `/100/101/102?pmin=42`
- Write Attributes `/100/101/102?pmax=514`

the `/100/101/102` Resource will have Attributes set to `pmin=42&pmax=514`. What is the expected way to reset the values of those Attributes so that the Attribute set for `/100/101/102` would be empty and notification on that resource would respect (and track) the rules set in the LWM2M Server Object "Default Minimum Period" and "Default Maximum Period" Resources? Is e.g. a `pmin=` syntax valid?

**Comment by ThGarnier** [comment]
Nothing is planned in TS 1.0 to reset that attributes yet; but your proposal makes sense, maybe not to reset to the default value, but just removing from the level where the attribute has been assigned (if no other assignation, so yes, it comes back on the default value). So in that case it is simpler and simple.
A proposal could be done in that sense, let this issue open for further status

**Comment by kFYatek** [comment]
Yes, "removing from the level where the attribute has been assigned" as you put it, is exactly what I meant. Sorry for my ambiguous wording.

**Comment by Megan-OMA** [comment]
Per ThGarnier comments above, this issue is now closed per proposal to the Working Group.
