### ISSUE TITLE
Format for Read/Write/Create operations

### ISSUE THREAD

**Issue by mkovatsc** [OpenMobileAlliance/OMA-LwM2M-Public-Review#9]
The TS should state that the CoAP Accept option is used to choose between different formats.
It should also be a "MUST" to include the CoAP Content-Format option for Write and Create operations.

Consequently, the Register Interface "MUST" also set the Content-Format to "application/link-format".

**Comment by jpradocueva** [comment]
Added labels to assist with the classification of the issue.

**Comment by ThGarnier** [comment]
This has been fixed in  CR09 (2015-02-12) and since then present in the current  TS 1.0
